//! SeaORM Entity. Generated by sea-orm-codegen 0.3.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "books_basket")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub total_price: Decimal,
    pub user_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::books_patron::Entity",
        from = "Column::UserId",
        to = "super::books_patron::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    BooksPatron,
}

impl Related<super::books_patron::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BooksPatron.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
