//! SeaORM Entity. Generated by sea-orm-codegen 0.3.1

pub use super::books_author::Entity as BooksAuthor;
pub use super::books_basket::Entity as BooksBasket;
pub use super::books_book::Entity as BooksBook;
pub use super::books_genre::Entity as BooksGenre;
pub use super::books_order::Entity as BooksOrder;
pub use super::books_patron::Entity as BooksPatron;
pub use super::books_publisher::Entity as BooksPublisher;
